### PR TITLE
Set new playlist index to the number of playlists for an offering

### LINKED ISSUE #46: Created new playlist should be pushed to the end of the playlists
The newly created playlist has its `index` default as `0`. It should be the length of the playlists in an offering, so that the newly added playlist can be placed at the end of the list.

### PR DESCRIPTION
**Pull request by asherdale**
Fixes #46

### CODE REVIEW

**Review by angrave — CHANGES_REQUESTED** [review]
If someone deletes a few intermediate playlists, causing current max index != count
 So how about the following instead of a count?
```
// If playlists are deleted the Count != Max Index, so use the max index
// still not perfect (what if 2 playlists are created at the same time)
if(  offering.Playlists.Count > 0) {
playlist.Index= 1+offering.Playlists.Max(p=>p.Index); // Guessing the correct syntax
// https://stackoverflow.com/questions/7542021/how-to-get-max-value-of-a-column-using-entity-framework
}
```

**Review by angrave — APPROVED** [review]

**Comment by angrave** [comment]
Please delete this branch once you are done with it.

**Comment by asherdale** [comment]
Just realized that this was accidentally merged into master instead of staging. Should we revert and merge into staging instead, or is it OK for now?

My bad on this.

**Comment by angrave** [comment]
Tested in production. Pulled it from master back to staging. So this branch can be deleted if you wish.

**Pull request merged**
