### PR TITLE
Angrave misc polish

### PR DESCRIPTION
**Pull request by angrave**
added vs_appsettings to .gitignore and forcibly removed the comment version
If you want to create your own local version any prefix is also ignored e.g. yourname_cs_appsettings.json

(Ideally we'd have a pre-commit hook to check that *vs_appsettings.json file and .env are never committed but I dont want to spend time learning how to do that)

Please don't delete this branch; I'm going to keep using it for small cleanup items as I find them

### CODE REVIEW

**Review by asherdale — COMMENTED** [review]
Is having an empty vs_appsettings.json file necessary for building the project? Or would it be possible to not create the file at all?

**Comment by angrave** [comment]
> Is having an empty vs_appsettings.json file necessary for building the project? Or would it be possible to not create the file at all?

It is necessary to exist. The dot net build command fails with a ‘missing vs_appsetting’ (or similar) error message. The file itself represents  a json dictionary of environment variables.

**Comment by houyuan2** [comment]
> Is having an empty vs_appsettings.json file necessary for building the project? Or would it be possible to not create the file at all?

I believe vs_appsettings.json is only used by the VS. I think it's possible to build docker images without it.

**Comment by houyuan2** [comment]
> > Is having an empty vs_appsettings.json file necessary for building the project? Or would it be possible to not create the file at all?
> 
> It is necessary to exist. The dot net build command fails with a ‘missing vs_appsetting’ (or similar) error message. The file itself represents a json dictionary of environment variables.

I thought that file is only used by VS. That's good to know

**Review by asherdale — APPROVED** [review]

**Comment by angrave** [comment]
@houyuan2  Yes any local version of your vs_appsetttings  _should_ be / must be ignored by the docker builds; we want our docker builds to get the env variables from the local .env file on the webserver. For the commit hooks, Rob was also building the code using a dotnet command and running unit tests (these builds are then discarded), before building the docker images,

**Pull request merged**
