### PR TITLE
Update controller unit tests

### PR DESCRIPTION
**Pull request by asherdale**
- Remove old tests in `CTServerTest`
- Add unit tests for ImagesController, CourseOfferingsController, and DepartmentsController
- Update unit tests for EPubsController and CoursesController
- Add global setup for unit tests with `GlobalFixture`, which includes mock auth service

### CODE REVIEW

**Review by angrave — CHANGES_REQUESTED** [review]
Hey looks like you're changing behavior of the backend
courses.count==0 -> NotFount
... and other 
Do we no longer want this behavior? If so please comment as such?
Does Rui/Frontend people @ruihuasui  know of this proposed change?
Did you check the front source code to say that this is non-breaking change; some code comments to explain why this is a safe change would be great
Oh wait... are you reverting a NotFound implementation from an earlier commit?

**Comment by ruihuasui** [comment]
Should we just return an empty array if the department id is valid but has no courses? Otherwise, it's kinda hard to distinguish the 404 error on "no such department id" or "no courses". The former one needs to report an error, but the 2nd is ok.

**Comment by asherdale** [comment]
> Hey looks like you're changing behavior of the backend
> courses.count==0 -> NotFount

I believe that's a change from a previous commit that I reverted in the last commit because I realized that I was changing the backend behavior. If you look at the most updated version of all of the controllers, none of the behavior is changed

**Comment by asherdale** [comment]
Looks like two tests are failing because the test asset files aren't being properly copied to the output directory, so the ImageControllerTests properly fail. It's working on my local machine so it's something with GitHub actions I guess, I'll look into it.

**Comment by angrave** [comment]
Github actions have min 10GB of space, Internet connectivity etc. So some quick ideas on possible differences: Your local machine may have settings in .env and vs_appsettings.json, and the data file base directory already exists.

**Comment by asherdale** [comment]
> Github actions have min 10GB of space, Internet connectivity etc. So some quick ideas on possible differences: Your local machine may have settings in .env and vs_appsettings.json, and the data file base directory already exists.

You were right, thank you for the pointers! There was a dependency on vs_appsettings.json because the tests needed a value for DATA_DIRECTORY. I removed the dependency on vs_appsettings.json and other environment variables, and the GlobalFixture explicitly defines a separate DATA_DIRECTORY for the tests which is cleaned up after the tests finish.

Now these changes are ready for review again.

**Review by angrave — APPROVED** [review]

**Comment by angrave** [comment]
You can merge now (and delete branch if you wish, or leave it open to add more tests)

**Comment by asherdale** [comment]
Screen Shot 2020-10-14 at 3 48 59 PM

I don't have the permissions to merge the PR, could you give me those permissions?

**Pull request merged**
