### PR TITLE
Hide unpublished offerings in students' feed

### LINKED ISSUE #167: Hide unpublished offerings in students' feed
Filter out the offerings w/ `publishStatus == 1` (i.e. unpublished) in `/api/Offerings/ByStudent`.

Please update the tests for this endpoint as well.

### PR DESCRIPTION
**Pull request by prktkn**
Fixes #167

### CODE REVIEW

**Comment by angrave** [comment]
What about existing offerings in the database? Wont they suddently be unpublished?

**Comment by prktkn** [comment]
@angrave I added a migration which I think solves this problem.

**Comment by angrave** [comment]
Okay thanks.  I see that will update all rows. What about new rows:

Do we have frontend ready to peform publishing and unpublishing offerings?
If I push this to the server what happens if/when new offering  are created tomorrow? Will it default to unpublished (and there be no way to publish it)?

Lawrence Angrave
Teaching Professor, Department of Computer Science
CITL Teaching Fellow
University of Illinois at Urbana-Champaign (UIUC)
T: 217 333 1424  E: angrave@illinois.edu

**Comment by asherdale** [comment]
@angrave it looks like this PR is stale, so I am happy to pick this up. To me, it looks like the first commit of this PR was enough to fix the problem, as the default value for `PublishStatus` in the DB is `Published` since the field is an enum (and `Published` corresponds to the 0 value, which is the default). I'll close this and create a new PR with an identical change to the first commit in this PR, since the second commit is unnecessary and the first commit doesn't have any effect on the existing offerings in the DB.

To double check on my logic about the existing offerings, I looked at pgAdmin on the dev site. I made the migration for creating the `PublishStatus` field in Dec 2020, and I can confirm that all offerings (including the ones created earlier than Dec 2020) have `PublishStatus` = 0 (which means `Published`). So only the first commit should be necessary.

**Pull request closed without merging**
