### PR TITLE
New Video entities should always have non-null JObject properties

### PR DESCRIPTION
**Pull request by asherdale**
First part of fixing #52

### CODE REVIEW

**Comment by asherdale** [comment]
I didn't want to include these tests in the `ControllerTests` folder, the only existing folder we have right now in the `UnitTests` project, because this is just testing the DB model. So I created a new folder `OtherTests` for miscellaneous tests like these, and in the future we can reorganize if we see more tests from a specific category. Let me know if you think the naming should be different.

**Comment by asherdale** [comment]
I tested this on my local machine by running the WebAPI, TaskEngine, and FrontEnd locally. I uploaded new videos to a playlist on the FrontEnd and confirmed on pgAdmin that the new Video rows in the DB had empty JObjects in the three columns instead of null values.

**Comment by angrave** [comment]
Excellent.  There's no old null db rows in production - 
SELECT count(*) FROM public."Medias" WHERE "JsonMetadata" is NULL
return 0; so we should be good.

**Review by angrave — APPROVED** [review]

**Comment by angrave** [comment]
https://github.com/classtranscribe/WebAPI/blob/cedcb53558e33510590aa4d3c47b73378c39a87c/TaskEngine/Tasks/QueueAwakerTask.cs#L192
Hmm we check if phrase hints are null to queue not-yet-done scenedetection

But I don't think there's any logic on FileMediainfo or SceneData. 

Can you do a grep/source check  on the C# code and python code to check?

In production SceneData FileMediaInfo null count is 1896 and 462.

**Comment by angrave** [comment]
FYI https://github.com/classtranscribe/WebAPI/blob/cedcb53558e33510590aa4d3c47b73378c39a87c/TaskEngine/Tasks/QueueAwakerTask.cs#L183 checks for a null Duration (which I believe is autoextracted from the FileMediaInfo data)

**Comment by angrave** [comment]
... so it may be safe to do the Update on FileMediaInfo without checking the code (e.g. Duration extraction)

**Pull request merged**
