### PR TITLE
ES task engine

### PR DESCRIPTION
**Pull request by houyuan2**
Preliminary PR to check if the new BuildElasticIndexTask is integrated correctly to the taskengine. The functionally of the new task still needs more testing.

### CODE REVIEW

**Comment by angrave** [comment]
Please resolve the conflicts first

**Comment by angrave** [comment]
This PR has conflicts. Please merge from current staging or close and submit as a new PR once conflicts have been fixed

**Comment by angrave** [comment]
FYI new conflicts :-)

**Comment by houyuan2** [comment]
I know, my first merge attempt is kind a disaster. I reverted the merge and gonna try again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by houyuan2** [comment]
Add the following line to .env if ports are closed:
ES_CONNECTION_ADDR=http://elasticsearch:9200

If ports are open:
ES_CONNECTION_ADDR=http://localhost:9200

Add the following line to vs_appsettings.json:
"ES_CONNECTION_ADDR": "http://localhost:9200"

**Comment by angrave** [comment]
I think your comment needs some addition comments! e.g. I assume ports will only need to be open during local development when running code directly in VS and not in Docker. 

It might be useful to explain how to do that in the overrides somewhere. Or to cross-reference the developer notes in docker-override.yml ...

**Comment by houyuan2** [comment]
Here is a sample of docker-compose.override.yml. It includes how to open ports and install dev tools such as pgadmin and kibana to containers. [https://github.com/classtranscribe/Deployment/blob/elastic_search_dev/docker-compose-override-README.txt](url)

**Comment by angrave** [comment]
I'll accept this. HOwever I noticed conditional in the later copy. Perhaps this should in the earlier include too? And maybe for the other projects too.

https://github.com/classtranscribe/WebAPI/blob/ad5d4ca63b7daa10e42eeae9e880ca5324533552/TaskEngine/TaskEngine.csproj#L40
  <ItemGroup Condition="Exists('..\vs_appsettings.json')">
    <Content Update="..\vs_appsettings.json" Link="vs_appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

L18-
  <ItemGroup>
    <Content Include="..\vs_appsettings.json" />
  </ItemGroup>

**Review by angrave — APPROVED** [review]

**Pull request merged**
