### PR TITLE
Allow instructors to create new course numbers on course creation

### LINKED ISSUE #15: Relax restriction on pre-allocated course number for course creation
You cant create a course if the course number for a department does not exist.
Allow instructors to just enter a 1-5 digit number if it does not exist already.

### PR DESCRIPTION
**Pull request by asherdale**
Fixes #15 

This allows instructors to create new course numbers on course creation on the backend. This is still unsupported on the frontend, but I will open an issue on the frontend once this has been merged.

### CODE REVIEW

**Review by angrave — APPROVED** [review]
Minor comment: I believe you could probably remove the duplication of where clause using FirstOrDefaultAsync()
and then add() the object it if you got a default object.

**Comment by asherdale** [comment]
> Minor comment: I believe you could probably remove the duplication of where clause using FirstOrDefaultAsync()
> and then add() the object it if you got a default object.

Makes sense, I'll update that now

**Comment by angrave** [comment]
Havent hit the big green button - that's up to Asher if he wants to refactor the code or not.

**Review by angrave — APPROVED** [review]

**Comment by angrave** [comment]
Merged. This might be good write a API test for using Rui Feng's SDK. e.g. Create a course without an existing number and with an existing number. Please delete this branch if you're finished with it.

**Pull request merged**
