### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by robkooper**
this should build the dotnet app as well as the containers. If staging or master branch these will be pushed to dockerhub

### CODE REVIEW

**Review by angrave — COMMENTED** [review]
Awesome awesomeness.

Please starting musing about how we can run / should run various unit tests and integration tests as part of this build process :-)
e.g. unit test classes in python, and C#
e.g. external tests that call the SDK 
e.g. Should we have a special .env or mode where there database is ephermal (not mounted)?

**Comment by robkooper** [comment]
right now the rpcserver.dockerfile:
a) does not work
b) does not have a start command

**Comment by robkooper** [comment]
it will now run tests (if any) as well as part of the build.

**Comment by angrave** [comment]
Merged. You can delete the branch (or I can)

**Pull request merged**
